// <auto-generated />
using System;
using CommonLibrary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommonLibrary.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250209224330_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommonLibrary.Models.DBModels.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "d5f1b6e1-4d56-4327-9056-b69e8d3db6f1",
                            CreatedOn = new DateTime(2024, 12, 9, 3, 35, 18, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@mail.com",
                            FirstName = "Jane",
                            Identifier = "e3a4f2c6-63b8-4d21-9eb8-06545e8f1a91",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "f3d10a2c-9b26-48cf-b385-5e7f9b1e3c8a",
                            CreatedOn = new DateTime(2024, 12, 29, 0, 27, 29, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@mail.com",
                            FirstName = "John",
                            Identifier = "b6a82c3b-8eb5-4b0c-b682-0f8e7c6d5a47",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "c4d27e3b-12a9-4f9e-81e6-f8a79b3d6c2d",
                            CreatedOn = new DateTime(2025, 1, 8, 17, 10, 59, 0, DateTimeKind.Unspecified),
                            Email = "bob.brown@mail.com",
                            FirstName = "Bob",
                            Identifier = "a2b97e46-7c5b-4485-b2a7-67e8c9f4d2b3",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "a7f6b3d2-8e4c-49a1-92f5-c7b6d3e8f2a1",
                            CreatedOn = new DateTime(2025, 1, 13, 3, 15, 10, 0, DateTimeKind.Unspecified),
                            Email = "charlie.white@mail.com",
                            FirstName = "Charlie",
                            Identifier = "9e3f4b6d-7b1c-4a28-a9f5-2b4c8d3e6f17",
                            LastName = "White"
                        },
                        new
                        {
                            Id = 5,
                            ConcurrencyStamp = "b9f5c7d3-6e4a-4b1f-82a7-3d2c8f4e1b7d",
                            CreatedOn = new DateTime(2025, 1, 14, 1, 21, 31, 0, DateTimeKind.Unspecified),
                            Email = "emma.green@mail.com",
                            FirstName = "Emma",
                            Identifier = "6b7d8e3c-4a1f-49a2-b9f5-1d3c7e8f2b6a",
                            LastName = "Green"
                        },
                        new
                        {
                            Id = 6,
                            ConcurrencyStamp = "c7d3b9f5-2e4a-4b1f-81a7-3d8c6f4e2b7d",
                            CreatedOn = new DateTime(2025, 1, 14, 18, 5, 58, 0, DateTimeKind.Unspecified),
                            Email = "david.black@mail.com",
                            FirstName = "David",
                            Identifier = "4e2b7d8f-3c6a-49a1-92f5-8d3e7b6c2f1a",
                            LastName = "Black"
                        },
                        new
                        {
                            Id = 7,
                            ConcurrencyStamp = "d3c7b9f5-8e4a-4b1f-81a7-2b8c6f4e7d3d",
                            CreatedOn = new DateTime(2025, 1, 30, 20, 22, 3, 0, DateTimeKind.Unspecified),
                            Email = "alice.johnson@mail.com",
                            FirstName = "Alice",
                            Identifier = "1b7d4e2c-8f6a-49a1-92f5-3d7c8b6f2e4a",
                            LastName = "Johnson"
                        });
                });

            modelBuilder.Entity("CommonLibrary.Models.DBModels.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExecutedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Trades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = 2,
                            AppUserId = 1,
                            ConcurrencyStamp = "d1be7005-0ca0-44ae-bdf9-e445ee111e56",
                            CreatedOn = new DateTime(2024, 12, 9, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2024, 12, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "e6b8c038-1b5c-4719-9317-7985920f1c0b",
                            Price = 160.00m,
                            Quantity = -1m,
                            Status = 4,
                            TotalAmount = -160.00m
                        },
                        new
                        {
                            Id = 2,
                            Action = 1,
                            AppUserId = 1,
                            ConcurrencyStamp = "12345d67-0285-4f4a-b536-b4a5ed94a75c",
                            CreatedOn = new DateTime(2024, 12, 12, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2024, 12, 12, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "e78db063-14c7-44c4-9b32-71a0b2d8a2b4",
                            Price = 266.00m,
                            Quantity = 1m,
                            Status = 3,
                            TotalAmount = 266.00m
                        },
                        new
                        {
                            Id = 3,
                            Action = 2,
                            AppUserId = 1,
                            ConcurrencyStamp = "885ff639-1d17-438d-92f0-3fc4a38e7f88",
                            CreatedOn = new DateTime(2024, 12, 12, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2024, 12, 12, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "33bb3074-4c52-4f02-9536-44317ed4a6a3",
                            Price = 162.00m,
                            Quantity = -1m,
                            Status = 3,
                            TotalAmount = -162.00m
                        },
                        new
                        {
                            Id = 4,
                            Action = 1,
                            AppUserId = 2,
                            ConcurrencyStamp = "4df4c218-b5b0-49d9-8b02-9b6b10fc1a2b",
                            CreatedOn = new DateTime(2025, 1, 2, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2025, 1, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "f9c1c4d1-1341-42cf-b927-871fa0a63d67",
                            Price = 150.00m,
                            Quantity = 1m,
                            Status = 3,
                            TotalAmount = 150.00m
                        },
                        new
                        {
                            Id = 5,
                            Action = 2,
                            AppUserId = 2,
                            ConcurrencyStamp = "4b6197b7-622f-4932-9b2d-3f243b1c15b3",
                            CreatedOn = new DateTime(2025, 1, 4, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2025, 1, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "98e2350b-9a56-42b0-a883-9ed3d1f7e831",
                            Price = 148.00m,
                            Quantity = -1m,
                            Status = 3,
                            TotalAmount = -148.00m
                        },
                        new
                        {
                            Id = 6,
                            Action = 2,
                            AppUserId = 3,
                            ConcurrencyStamp = "dc7b9b04-16ab-4790-8e6e-ff3e7ad9ca61",
                            CreatedOn = new DateTime(2025, 1, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2025, 1, 8, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "93bb0b7d-1f92-44d7-9be7-fc4f60c7d4e3",
                            Price = 145.00m,
                            Quantity = -1m,
                            Status = 4,
                            TotalAmount = -145.00m
                        },
                        new
                        {
                            Id = 7,
                            Action = 1,
                            AppUserId = 3,
                            ConcurrencyStamp = "6d71248a-e5f1-4d60-95c4-4ac1f1d7136b",
                            CreatedOn = new DateTime(2025, 1, 10, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2025, 1, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "8f17e1fc-022f-4c65-83a9-d7bb982d6175",
                            Price = 142.00m,
                            Quantity = 1m,
                            Status = 3,
                            TotalAmount = 142.00m
                        },
                        new
                        {
                            Id = 8,
                            Action = 1,
                            AppUserId = 7,
                            ConcurrencyStamp = "dfbd15b7-2b4d-4c48-bf26-90d9a3f60c92",
                            CreatedOn = new DateTime(2025, 1, 31, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2025, 1, 31, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "dff57d0c-bc91-40a3-b97f-5fbdfe48898b",
                            Price = 150.00m,
                            Quantity = 1m,
                            Status = 3,
                            TotalAmount = 150.00m
                        },
                        new
                        {
                            Id = 9,
                            Action = 1,
                            AppUserId = 7,
                            ConcurrencyStamp = "bc889cb3-cf64-4d22-b62e-b424c26db689",
                            CreatedOn = new DateTime(2025, 2, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2025, 2, 2, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "ab1cb59e-cc2f-4011-b139-e0d3f067f6b2",
                            Price = 155.00m,
                            Quantity = 1m,
                            Status = 3,
                            TotalAmount = 155.00m
                        },
                        new
                        {
                            Id = 10,
                            Action = 1,
                            AppUserId = 2,
                            ConcurrencyStamp = "8b28166f-8f31-4ed1-b83a-1dffb79ca098",
                            CreatedOn = new DateTime(2025, 2, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2025, 2, 3, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "ceac11db-4602-4e73-bd1b-b1db599241a6",
                            Price = 198.00m,
                            Quantity = 1m,
                            Status = 3,
                            TotalAmount = 198.00m
                        },
                        new
                        {
                            Id = 11,
                            Action = 1,
                            AppUserId = 1,
                            ConcurrencyStamp = "47fae6c8-e6b7-4774-b087-c9a22d508038",
                            CreatedOn = new DateTime(2025, 2, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2025, 2, 5, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "a1b1b01b-ffec-40ea-b18a-5c711fd650be",
                            Price = 160.00m,
                            Quantity = 1m,
                            Status = 3,
                            TotalAmount = 160.00m
                        },
                        new
                        {
                            Id = 12,
                            Action = 2,
                            AppUserId = 3,
                            ConcurrencyStamp = "9787b0d9-b457-42d1-b1d7-80fe02858f7d",
                            CreatedOn = new DateTime(2025, 2, 6, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2025, 2, 6, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "3ca91f67-c8b1-463a-9de4-660b0a9c4187",
                            Price = 145.00m,
                            Quantity = -1m,
                            Status = 4,
                            TotalAmount = -145.00m
                        },
                        new
                        {
                            Id = 13,
                            Action = 1,
                            AppUserId = 7,
                            ConcurrencyStamp = "1ac8f717-0d39-45db-b85b-6f33e0b4d6e6",
                            CreatedOn = new DateTime(2025, 2, 7, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2025, 2, 7, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "e11b0517-cbd4-4ed4-99bc-5fffd3c74c26",
                            Price = 155.00m,
                            Quantity = 1m,
                            Status = 3,
                            TotalAmount = 155.00m
                        },
                        new
                        {
                            Id = 14,
                            Action = 1,
                            AppUserId = 4,
                            ConcurrencyStamp = "a6e3ff48-5b96-43fa-8272-77c5c5c7f3f6",
                            CreatedOn = new DateTime(2025, 2, 8, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2025, 2, 8, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "c7359007-6a82-4e39-8d13-22c8ecb2ac80",
                            Price = 140.00m,
                            Quantity = 1m,
                            Status = 3,
                            TotalAmount = 140.00m
                        },
                        new
                        {
                            Id = 15,
                            Action = 1,
                            AppUserId = 5,
                            ConcurrencyStamp = "c56d62ea-cd06-476a-b1f7-28930769be91",
                            CreatedOn = new DateTime(2025, 2, 8, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2025, 2, 8, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "b2764f66-5c72-4b69-b44c-7d244bde6078",
                            Price = 152.00m,
                            Quantity = 1m,
                            Status = 3,
                            TotalAmount = 152.00m
                        },
                        new
                        {
                            Id = 16,
                            Action = 1,
                            AppUserId = 2,
                            ConcurrencyStamp = "4ec2b2ba-bbdb-47a7-bbb6-4aeb2019e96a",
                            CreatedOn = new DateTime(2025, 2, 10, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2025, 2, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "da9670b4-d45a-49b0-a383-b79db3e47a4f",
                            Price = 153.00m,
                            Quantity = 1m,
                            Status = 3,
                            TotalAmount = 153.00m
                        },
                        new
                        {
                            Id = 17,
                            Action = 2,
                            AppUserId = 6,
                            ConcurrencyStamp = "93db3d2c-c93c-4db2-babf-bf92e7e6da97",
                            CreatedOn = new DateTime(2025, 2, 11, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2025, 2, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "d3d4ab3b-0e76-43e5-b37d-1fa1b3f1c989",
                            Price = 165.00m,
                            Quantity = -1m,
                            Status = 4,
                            TotalAmount = -165.00m
                        },
                        new
                        {
                            Id = 18,
                            Action = 1,
                            AppUserId = 5,
                            ConcurrencyStamp = "70b264a3-e79f-4a0c-b8e2-8e6f1a9d8fe5",
                            CreatedOn = new DateTime(2025, 2, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ExecutedOn = new DateTime(2025, 2, 12, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "9c2f67cf-6267-4c31-9b5b-059f9f2787b9",
                            Price = 150.00m,
                            Quantity = 1m,
                            Status = 3,
                            TotalAmount = 150.00m
                        });
                });

            modelBuilder.Entity("CommonLibrary.Models.DBModels.Trade", b =>
                {
                    b.HasOne("CommonLibrary.Models.DBModels.AppUser", "AppUser")
                        .WithMany("Trades")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("CommonLibrary.Models.DBModels.AppUser", b =>
                {
                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
